version: '3.8'

services:
  customer-service:
    build: ./CustomerService
    ports:
      - 3000:3000
    networks:
      - micronet
    depends_on:
      - rabbitmq
      - mongo
  
  product-service:
    build: ./ProductService
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - micronet
  
  payment-service:
    build: ./PaymentService
    depends_on:
      - rabbitmq
    networks:
      - micronet
  
  order-service:
    build: ./OrderService
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - micronet

  transaction-service:
    build: ./TransactionService
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - micronet
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks: 
      - micronet

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - micronet

volumes:
  mongodb: 

networks:
  micronet:
    driver: bridge
