version: '3.8'

services:
  customer-service:
    build: ./CustomerService
    command: npm start
    ports:
      - 3000:3000
    links:
      - mongo
      - rabbit
    networks:
      - rabbit-net
    depends_on:
      - rabbit
      - product-service
      - mongo
  
  product-service:
    build: ./ProductService
    command: npm start
    depends_on:
      - rabbit
      - mongo
    networks:
      - rabbit-net
    links:
      - mongo
      - rabbit

  order-service:
    build: ./OrderService
    command: npm start
    depends_on:
      - rabbit
      - mongo
    networks:
      - rabbit-net
    links:
      - mongo
      - rabbit
    
  payment-service:
    build: ./PaymentService
    command: npm start
    networks:
      - rabbit-net
    depends_on:
      - rabbit
    links:
      - rabbit

  transaction-service:
    build: ./TransactionService
    command: npm start
    networks:
      - rabbit-net
    depends_on:
      - rabbit
      - mongo
    links:
      - mongo
      - rabbit
    
  rabbit:
    image: rabbitmq
    container_name: "rabbit"
    ports:
      - 5672:5672
    networks: 
      - rabbit-net
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/volumes
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - rabbit-net

volumes:
  mongodb:

networks:
  rabbit-net:
    driver: bridge

      
    
